// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderManagementApp;

#nullable disable

namespace OrderManagementApp.Migrations
{
    [DbContext(typeof(OrderDbContext))]
    partial class OrderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrderManagementApp.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerEmail")
                        .IsUnique();

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("ProductId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OrderManagementApp.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "General",
                            CreatedAt = new DateTime(2026, 1, 21, 16, 17, 35, 910, DateTimeKind.Local).AddTicks(9985),
                            Name = "Product 1",
                            Price = 100m,
                            Sku = "SKU-001",
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 2,
                            Category = "General",
                            CreatedAt = new DateTime(2026, 1, 21, 16, 17, 35, 911, DateTimeKind.Local).AddTicks(6208),
                            Name = "Product 2",
                            Price = 200m,
                            Sku = "SKU-002",
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 3,
                            Category = "General",
                            CreatedAt = new DateTime(2026, 1, 21, 16, 17, 35, 911, DateTimeKind.Local).AddTicks(6331),
                            Name = "Product 3",
                            Price = 300m,
                            Sku = "SKU-003",
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 4,
                            Category = "General",
                            CreatedAt = new DateTime(2026, 1, 21, 16, 17, 35, 911, DateTimeKind.Local).AddTicks(6347),
                            Name = "Product 4",
                            Price = 400m,
                            Sku = "SKU-004",
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 5,
                            Category = "General",
                            CreatedAt = new DateTime(2026, 1, 21, 16, 17, 35, 911, DateTimeKind.Local).AddTicks(6361),
                            Name = "Product 5",
                            Price = 500m,
                            Sku = "SKU-005",
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 6,
                            Category = "General",
                            CreatedAt = new DateTime(2026, 1, 21, 16, 17, 35, 911, DateTimeKind.Local).AddTicks(6380),
                            Name = "Product 6",
                            Price = 600m,
                            Sku = "SKU-006",
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 7,
                            Category = "General",
                            CreatedAt = new DateTime(2026, 1, 21, 16, 17, 35, 911, DateTimeKind.Local).AddTicks(6393),
                            Name = "Product 7",
                            Price = 700m,
                            Sku = "SKU-007",
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 8,
                            Category = "General",
                            CreatedAt = new DateTime(2026, 1, 21, 16, 17, 35, 911, DateTimeKind.Local).AddTicks(6406),
                            Name = "Product 8",
                            Price = 800m,
                            Sku = "SKU-008",
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 9,
                            Category = "General",
                            CreatedAt = new DateTime(2026, 1, 21, 16, 17, 35, 911, DateTimeKind.Local).AddTicks(6419),
                            Name = "Product 9",
                            Price = 900m,
                            Sku = "SKU-009",
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 10,
                            Category = "General",
                            CreatedAt = new DateTime(2026, 1, 21, 16, 17, 35, 911, DateTimeKind.Local).AddTicks(6438),
                            Name = "Product 10",
                            Price = 1000m,
                            Sku = "SKU-010",
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 11,
                            Category = "General",
                            CreatedAt = new DateTime(2026, 1, 21, 16, 17, 35, 911, DateTimeKind.Local).AddTicks(6452),
                            Name = "Product 11",
                            Price = 1100m,
                            Sku = "SKU-011",
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 12,
                            Category = "General",
                            CreatedAt = new DateTime(2026, 1, 21, 16, 17, 35, 911, DateTimeKind.Local).AddTicks(6466),
                            Name = "Product 12",
                            Price = 1200m,
                            Sku = "SKU-012",
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 13,
                            Category = "General",
                            CreatedAt = new DateTime(2026, 1, 21, 16, 17, 35, 911, DateTimeKind.Local).AddTicks(6478),
                            Name = "Product 13",
                            Price = 1300m,
                            Sku = "SKU-013",
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 14,
                            Category = "General",
                            CreatedAt = new DateTime(2026, 1, 21, 16, 17, 35, 911, DateTimeKind.Local).AddTicks(6490),
                            Name = "Product 14",
                            Price = 1400m,
                            Sku = "SKU-014",
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 15,
                            Category = "General",
                            CreatedAt = new DateTime(2026, 1, 21, 16, 17, 35, 911, DateTimeKind.Local).AddTicks(6504),
                            Name = "Product 15",
                            Price = 1500m,
                            Sku = "SKU-015",
                            StockQuantity = 100
                        });
                });

            modelBuilder.Entity("OrderManagementApp.Order", b =>
                {
                    b.HasOne("OrderManagementApp.Product", "Product")
                        .WithMany("Orders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OrderManagementApp.Product", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
